### ISSUE TITLE
老哥，第40行是不是应该用reshape啊？

### ISSUE THREAD

**Issue by RichardHWD** [yatengLG/Focal-Loss-Pytorch#1]
老哥的代码看起来很舒服啊，但是用的时候第40行preds = preds.view(-1,preds.size(-1))报错了，改成reshape就通过了。正在使用，你看看是不是这样改，我也怕等等训爆炸了2333

**Comment by yatengLG** [comment]
tensor才有view方法,你输入的应该不是tensor.刚上传了使用例子,后续会添加详细的计算流程及说明

**Comment by yatengLG** [comment]
昨天上传了使用例子, view的问题应该是传入的不是张量tensor引起的.  今天用这个损失函数刚训练了SSD,没有问题,可以放心使用.
