### ISSUE TITLE
图像分割使用问题

### ISSUE THREAD

**Issue by huweiv** [yatengLG/Focal-Loss-Pytorch#11]
您好，打扰您了，想请教一下该损失函数能用于图像分割吗，我直接使用会报关于维度的错误。

**Comment by yatengLG** [comment]
是可以使用的，已经在点云分割任务使用过了。

关于维度报错的问题，这里建议都拉成一维再使用，eg:[B,n]。

**Comment by huweiv** [comment]
好的，感谢您的回答。

**Comment by SC-shendazt** [comment]
> 是可以使用的，已经在点云分割任务使用过了。
> 
> 关于维度报错的问题，这里建议都拉成一维再使用，eg:[B,n]。

点云中有效果吗，如果做语义分割
