### ISSUE TITLE
NER中num_class怎么设置？

### ISSUE THREAD

**Issue by Smile-L-up** [yatengLG/Focal-Loss-Pytorch#13]
您好，感谢您的分享。想请教一下，在NER任务中，比如有['O','B-person','I-person','[PAD]','[CLS]','[SEP]']这几个标签，num_class应该设置多少？还有就是NER中preds和labels的输入是？可以举个例子么？

**Comment by DOQQLOL** [comment]
`        total_num = float(sum(classes_num))
        classes_w_t1 = [ total_num / ff for ff in classes_num ]
        sum_ = sum(classes_w_t1)
        classes_w_t2 = [ ff/sum_ for ff in classes_w_t1 ]   #scale
        classes_w_tensor = tf.convert_to_tensor(classes_w_t2, dtype=prediction_tensor.dtype)
   `

可以参照这个来更
