### ISSUE TITLE
当batch size是1的时候报错

### ISSUE THREAD

**Issue by lx9cat** [yatengLG/Focal-Loss-Pytorch#15]
在代码中把batchsize设置为1，在第二个batch的时候，运行过        self.alpha = self.alpha.gather(0, labels.view(-1))
这句代码之后，会报越界错误，具体表现为所有tensor的值都会变成Unable to get repr for <class 'torch.Tensor'>。应该怎么更改呢？

**Comment by yatengLG** [comment]
这个是bug，已经更新了。

https://github.com/yatengLG/Focal-Loss-Pytorch/issues/9#issuecomment-751473941
