### ISSUE TITLE
alpha如何设置？

### ISSUE THREAD

**Issue by ChenXiao61** [yatengLG/Focal-Loss-Pytorch#2]
你好，我在做图片5分类，数目分别是A类280张 、C类 313 、D类1801 、G类 326和N类 2157，想解决数据不平衡问题，我的alpha和gamma怎么设置呢？期待您的回复！

**Comment by yatengLG** [comment]
你这种情况, alpha  传入 一个 列表.
你这个是五分类, 如:

alpha = [1,1,2,1,5]
这样就会把第5类加强5倍, 第3类 加强2倍.这个你可以先训练下,在看着设置具体参数.

**Comment by yatengLG** [comment]
具体设置情况可以参见例子:https://github.com/yatengLG/Focal-Loss-Pytorch/blob/master/Demo.ipynb

另外,你这是分类问题,由于有γ值处理难分样本,分类问题容易过拟合,建议在优化器中添加正则化,扛过拟合.

**Comment by ChenXiao61** [comment]
好滴！我数据少，也没有数据增强，用的迁移学习只微调最后一次，用一下你写的focal_loss试一下😄



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yatengLG <notifications@github.com&gt;
发送时间: 2019年10月31日 16:35
收件人: yatengLG/Focal-Loss-Pytorch <Focal-Loss-Pytorch@noreply.github.com&gt;
抄送: Chen Xiao <mylovechenxiao@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[yatengLG/Focal-Loss-Pytorch] alpha如何设置？ (#2)




具体设置情况可以参见例子:https://github.com/yatengLG/Focal-Loss-Pytorch/blob/master/Demo.ipynb
 
另外,你这是分类问题,由于有γ值处理难分样本,分类问题容易过拟合,建议在优化器中添加正则化,扛过拟合.

**Comment by ChenXiao61** [comment]
非常感谢你！加上5倍是什么意思？我刚刚设置为[7, 7, 1，7，1]，loss值比之前低了，但是准确度升不上去怎么回事呢？感谢您的回复！

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yatengLG <notifications@github.com&gt;
发送时间: 2019年10月31日 16:32
收件人: yatengLG/Focal-Loss-Pytorch <Focal-Loss-Pytorch@noreply.github.com&gt;
抄送: Chen Xiao <mylovechenxiao@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[yatengLG/Focal-Loss-Pytorch] alpha如何设置？ (#2)

**Comment by yatengLG** [comment]
你说的准确率上不去是 训练集还是测试集?

你输出 训练集准确率和 测试集准确率 看一下, 是不是 已经过拟合了.

**Comment by ChenXiao61** [comment]
没有过拟合，训练集和测试集的准确度都在50%多，用了focal loss以后loss值确实变低了了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yatengLG <notifications@github.com&gt;
发送时间: 2019年10月31日 16:52
收件人: yatengLG/Focal-Loss-Pytorch <Focal-Loss-Pytorch@noreply.github.com&gt;
抄送: Chen Xiao <mylovechenxiao@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[yatengLG/Focal-Loss-Pytorch] alpha如何设置？ (#2)




你说的准确率上不去是 训练集还是测试集?
 
你输出 训练集准确率和 测试集准确率 看一下, 是不是 已经过拟合了.

**Comment by yatengLG** [comment]
你用的啥网络啊,50%可是真的低啊.....你多训练几轮看看情况? 你用交叉熵多少准确率

**Comment by ChenXiao61** [comment]
用的efficientnet，只训练最后一层，是不是我迭代太少了，训练集也太低了

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yatengLG <notifications@github.com&gt;
发送时间: 2019年10月31日 17:18
收件人: yatengLG/Focal-Loss-Pytorch <Focal-Loss-Pytorch@noreply.github.com&gt;
抄送: Chen Xiao <mylovechenxiao@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[yatengLG/Focal-Loss-Pytorch] alpha如何设置？ (#2)




你用的啥网络啊,50%可是真的低啊.....你多训练几轮看看情况? 你用交叉熵多少准确率

**Comment by ChenXiao61** [comment]
交叉熵和focal loss在训练集和测试集的准确度差不多。训练集准确度63%，测试集是58%，应该是欠拟合吧。我之前二分类10epochs以内就收敛了，5分类是需要多迭代吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yatengLG <notifications@github.com&gt;
发送时间: 2019年10月31日 17:18
收件人: yatengLG/Focal-Loss-Pytorch <Focal-Loss-Pytorch@noreply.github.com&gt;
抄送: Chen Xiao <mylovechenxiao@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[yatengLG/Focal-Loss-Pytorch] alpha如何设置？ (#2)




你用的啥网络啊,50%可是真的低啊.....你多训练几轮看看情况? 你用交叉熵多少准确率

**Comment by ChenXiao61** [comment]
在4，5次epochs以后loss也确实没多大变化了

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yatengLG <notifications@github.com&gt;
发送时间: 2019年10月31日 17:18
收件人: yatengLG/Focal-Loss-Pytorch <Focal-Loss-Pytorch@noreply.github.com&gt;
抄送: Chen Xiao <mylovechenxiao@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[yatengLG/Focal-Loss-Pytorch] alpha如何设置？ (#2)




你用的啥网络啊,50%可是真的低啊.....你多训练几轮看看情况? 你用交叉熵多少准确率

**Comment by yatengLG** [comment]
你这是把前的权重只是加载了,还是冻结了.我刚试这训练了下,损失函数没问题的

**Comment by yatengLG** [comment]
![图片](https://user-images.githubusercontent.com/31759824/67936080-0ecf9800-fc06-11e9-8487-b578e60685e0.png
损失函数确实是没问题的.如果你交叉熵也还是 50%左右的话, 就是你模型的问题, 或者你这个迁移有问题. 迁移的前提的俩数据集在分布上有相似处,如果毫无相关的俩个数据集,效果就差了.  你如果是冻结了前面,只训练最后一层的话,效果差是很肯定的.

**Comment by yatengLG** [comment]
![图片](https://user-images.githubusercontent.com/31759824/67936260-6bcb4e00-fc06-11e9-8fec-6ad474a669fe.png)

**Comment by ChenXiao61** [comment]
嗯嗯，我是只微调了最后全连接层，数据相差比较大。现在微调整个模型看看

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yatengLG <notifications@github.com&gt;
发送时间: 2019年10月31日 17:47
收件人: yatengLG/Focal-Loss-Pytorch <Focal-Loss-Pytorch@noreply.github.com&gt;
抄送: Chen Xiao <mylovechenxiao@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[yatengLG/Focal-Loss-Pytorch] alpha如何设置？ (#2)

**Comment by ChenXiao61** [comment]
我微调了整个模型，训练集的准确度不断增大loss也减小。但是验证集的loss不怎么下降了

这个alpha给数目越少的类别权重越大吧，哪里的问题呢？

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yatengLG <notifications@github.com&gt;
发送时间: 2019年10月31日 17:47
收件人: yatengLG/Focal-Loss-Pytorch <Focal-Loss-Pytorch@noreply.github.com&gt;
抄送: Chen Xiao <mylovechenxiao@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[yatengLG/Focal-Loss-Pytorch] alpha如何设置？ (#2)

**Comment by yatengLG** [comment]
是给数目小的类别更大的权重.但是为啥要看验证集损失呢?
训练不是只需要观察训练集损失是否在收敛,来确定模型是否在更新.
然后通过训练集准确率 以及 测试集准确率 来判断模型拟合程度么?

**Comment by ChenXiao61** [comment]
验证集是在训练的时候看模型的预测情况，和最后测试集结果差不多。我微调了整个模型，focal loss还不如交叉验证的，alpha和gamma怎么设置呢？

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yatengLG <notifications@github.com&gt;
发送时间: 2019年11月1日 09:21
收件人: yatengLG/Focal-Loss-Pytorch <Focal-Loss-Pytorch@noreply.github.com&gt;
抄送: Chen Xiao <mylovechenxiao@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[yatengLG/Focal-Loss-Pytorch] alpha如何设置？ (#2)




是给数目小的类别更大的权重.但是为啥要看验证集损失呢?
 训练不是只需要观察训练集损失是否在收敛,来确定模型是否在更新.
 然后通过训练集准确率 以及 测试集准确率 来判断模型拟合程度么?

**Comment by yijie422** [comment]
> 你这种情况, alpha  传入 一个 列表.
> 你这个是五分类, 如:
> alpha = [1,1,2,1,5]
> 这样就会把第5类加强5倍, 第3类 加强2倍.这个你可以先训练下,在看着设置具体参数.

您好，这里有个问题，为什么数目多的要增强呢？不是应该衰减吗？

**Comment by yatengLG** [comment]
@yijie422 这里先说一下，这个 alpha是增强的权重，alpha = [1,1,2,1,5] 这个的意思就是 第1,2,4 类不加强，第3类加强二倍，第5类加强五倍。  这个只是举个例子啊 T.T   。你看人家都理解了，自己设置了[7, 7, 1，7，1]  ..........
