### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by 18022443868** [yatengLG/Focal-Loss-Pytorch#6]
Can't this loss be used for RGB as input for image training

**Comment by 18022443868** [comment]
The above CUDA errors occur in training

**Comment by yatengLG** [comment]
Please provide the running environment and part of the loss function code.

another way, you can run this example to verify the  loss function code.
https://github.com/yatengLG/Focal-Loss-Pytorch/blob/master/Demo.ipynb
