### ISSUE TITLE
alpha bug

### ISSUE THREAD

**Issue by suluo** [yatengLG/Focal-Loss-Pytorch#9]
Hi, yatengLG
对于focal_loss中
self.alpha = self.alpha.gather(0,labels.view(-1))

假设多分类num_classes=10，batch_size=8
第一轮self.alpha.size=10， 第二轮self.alpha=8，这好像是bug吧

**Comment by YuchaoZheng** [comment]
应该改成alpha = self.alpha.gather(0,labels.view(-1))
